steps:
- id: 'create new repo'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      REPO=("repo1" "repo2" "repo3")
      i=1
      while [ "$i" -le 2 ];
      do
      curl \
      -i -H "Authorization: token  $$EXP_TOKEN" \
      -d '{"name":"'"$REPO"'", "private": false}' \
      https://api.github.com/user/repos
      j=0
      len=${#REPO[@]}
      while [ "$j" -le $len ];
      do
          echo ${REPO[$j]};
      i=$(( j + 1 ))
      done
      i=$(( i + 1 ))
      sleep 10
      done
  secretEnv: ['EXP_TOKEN']

# substitutions:
#     _REPO: (repo1, repo2)

availableSecrets:
  secretManager:
  - versionName: projects/719645512214/secrets/EXP_TOKEN/versions/1
    env: 'EXP_TOKEN'
timeout: 6600s
