steps:
- id: 'create new repo'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      repo=(${_REPO//,/ })
      for i in "${repo[@]}"
      do
        echo $i
       done
#       i=1
#       j=1
#       while [ "$i" -le 2 ];
#       do
#       curl \
#       -i -H "Authorization: token  $$EXP_TOKEN" \
#       -d '{"name":"'"repo_$j"'", "private": false}' \
#       https://api.github.com/user/repos
#       sleep 10
#       i=$(( i + 1 ))
# #       j=$(( j + 1 ))
#       done
  secretEnv: ['EXP_TOKEN']

substitutions:
    _REPO: repo1, repo2

availableSecrets:
  secretManager:
  - versionName: projects/719645512214/secrets/EXP_TOKEN/versions/1
    env: 'EXP_TOKEN'
timeout: 6600s
