steps:
- id: 'create new repo'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      chmod +x script.sh
      ./script.sh

  secretEnv: ['EXP_TOKEN']

substitutions:
    _REPO: repo1,repo2,repo3

availableSecrets:
  secretManager:
  - versionName: projects/719645512214/secrets/EXP_TOKEN/versions/1
    env: 'EXP_TOKEN'
timeout: 6600s
