steps:
- id: 'create new repo'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      max=2
      for i in `seq 2 $max`
      do  
      curl \
      -i -H "Authorization: token  $$EXP_TOKEN" \
      -d '{"name":"'"$_REPO"'", "private": false}' \
      https://api.github.com/user/repos
      done
  secretEnv: ['EXP_TOKEN']

substitutions:
    _REPO: repo1
    

availableSecrets:
  secretManager:
  - versionName: projects/719645512214/secrets/EXP_TOKEN/versions/1
    env: 'EXP_TOKEN'
timeout: 6600s
