steps:
- id: 'create new repo'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      chmod +x script.sh
      ./script.sh
      export co=$(./script.sh)
      echo $co
      curl \
      -X PUT -H "Authorization: token  $$EXP_TOKEN" "Accept: application/vnd.github.v3+json" \
      https://api.github.com/repos/Kaware-Pratik/Experiment/contents/CODEOWNERS \
      -d '{"message":"message","content":"'"$co"'"}'
      echo $co
  secretEnv: ['EXP_TOKEN']

substitutions:
    _REPO: repo1,repo2,repo3

availableSecrets:
  secretManager:
  - versionName: projects/719645512214/secrets/EXP_TOKEN/versions/1
    env: 'EXP_TOKEN'
timeout: 6600s
